-- Weight log entries table
-- Stores individual weight measurements over time

CREATE TABLE weight_logs (
  -- Primary key: UUID generated by postgres
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- When the weight was measured (user-provided, with timezone)
  datetime TIMESTAMPTZ NOT NULL,
  
  -- The weight value, up to 9999.99
  weight NUMERIC(6,2) NOT NULL,
  
  -- Unit of measurement, constrained to valid values
  unit VARCHAR(3) NOT NULL CHECK (unit IN ('lbs', 'kg')),
  
  -- Optional notes
  notes TEXT,
  
  -- Audit timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for efficient date-based queries (most recent first)
CREATE INDEX idx_weight_logs_datetime ON weight_logs(datetime DESC);

-- Trigger to auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_weight_logs_updated_at
  BEFORE UPDATE ON weight_logs
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
