-- Injection log entries table
-- Stores individual injection events for medication tracking

CREATE TABLE injection_logs (
  -- Primary key: UUID generated by postgres
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- When the injection was administered
  datetime TIMESTAMPTZ NOT NULL,
  
  -- Name of the drug/compound
  drug VARCHAR(255) NOT NULL,
  
  -- Source/pharmacy (optional)
  source VARCHAR(255),
  
  -- Dosage as string (e.g., "200mg", "0.5ml")
  dosage VARCHAR(100) NOT NULL,
  
  -- Body location of injection (optional)
  injection_site VARCHAR(100),
  
  -- Optional notes
  notes TEXT,
  
  -- Audit timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for efficient date-based queries
CREATE INDEX idx_injection_logs_datetime ON injection_logs(datetime DESC);

-- Index for filtering by drug name
CREATE INDEX idx_injection_logs_drug ON injection_logs(drug);

-- Use the same updated_at trigger function from weight_logs migration
CREATE TRIGGER update_injection_logs_updated_at
  BEFORE UPDATE ON injection_logs
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
