import { Schema } from 'effect'
import { Dosage, DrugName, DrugSource, InjectionLogId, InjectionSite, Limit, Notes, Offset } from './Brand.js'

// ============================================
// Core Domain Type
// ============================================

/**
 * An injection log entry represents a single injection event.
 * Used for tracking medication injections (TRT, peptides, etc.)
 *
 * @property id - UUID, generated by database
 * @property datetime - When the injection was administered
 * @property drug - Name of the drug/compound (e.g., "Testosterone Cypionate")
 * @property source - Where the drug came from (e.g., "CVS", "Empower Pharmacy")
 * @property dosage - Amount injected as string (e.g., "200mg", "0.5ml")
 * @property injectionSite - Body location (e.g., "left ventrogluteal", "right deltoid")
 * @property notes - Optional free-text notes
 * @property createdAt - When this record was created
 * @property updatedAt - When this record was last modified
 */
export class InjectionLog extends Schema.Class<InjectionLog>('InjectionLog')({
  id: InjectionLogId,
  datetime: Schema.Date,
  drug: DrugName,
  source: Schema.NullOr(DrugSource),
  dosage: Dosage,
  injectionSite: Schema.NullOr(InjectionSite),
  notes: Schema.NullOr(Notes),
  createdAt: Schema.Date,
  updatedAt: Schema.Date,
}) {}

// ============================================
// Input Types
// ============================================

/**
 * Payload for creating a new injection log entry.
 */
export class InjectionLogCreate extends Schema.Class<InjectionLogCreate>('InjectionLogCreate')({
  datetime: Schema.Date,
  drug: DrugName,
  source: Schema.optionalWith(DrugSource, { as: 'Option' }),
  dosage: Dosage,
  injectionSite: Schema.optionalWith(InjectionSite, { as: 'Option' }),
  notes: Schema.optionalWith(Notes, { as: 'Option' }),
}) {}

/**
 * Payload for updating an existing injection log entry.
 */
export class InjectionLogUpdate extends Schema.Class<InjectionLogUpdate>('InjectionLogUpdate')({
  id: InjectionLogId,
  datetime: Schema.optional(Schema.Date),
  drug: Schema.optional(DrugName),
  source: Schema.optionalWith(Schema.NullOr(DrugSource), { as: 'Option' }),
  dosage: Schema.optional(Dosage),
  injectionSite: Schema.optionalWith(Schema.NullOr(InjectionSite), {
    as: 'Option',
  }),
  notes: Schema.optionalWith(Schema.NullOr(Notes), { as: 'Option' }),
}) {}

/**
 * Payload for deleting an injection log entry.
 */
export class InjectionLogDelete extends Schema.Class<InjectionLogDelete>('InjectionLogDelete')({
  id: InjectionLogId,
}) {}

/**
 * Parameters for listing injection logs.
 */
export class InjectionLogListParams extends Schema.Class<InjectionLogListParams>('InjectionLogListParams')({
  limit: Schema.optionalWith(Limit, { default: () => 50 as Limit }),
  offset: Schema.optionalWith(Offset, { default: () => 0 as Offset }),
  startDate: Schema.optional(Schema.Date),
  endDate: Schema.optional(Schema.Date),
  drug: Schema.optional(DrugName), // Filter by specific drug
}) {}
