import { Schema } from 'effect'

// ============================================
// Core Domain Type
// ============================================

/**
 * An injection log entry represents a single injection event.
 * Used for tracking medication injections (TRT, peptides, etc.)
 *
 * @property id - UUID, generated by database
 * @property datetime - When the injection was administered
 * @property drug - Name of the drug/compound (e.g., "Testosterone Cypionate")
 * @property source - Where the drug came from (e.g., "CVS", "Empower Pharmacy")
 * @property dosage - Amount injected as string (e.g., "200mg", "0.5ml")
 * @property injectionSite - Body location (e.g., "left ventrogluteal", "right deltoid")
 * @property notes - Optional free-text notes
 * @property createdAt - When this record was created
 * @property updatedAt - When this record was last modified
 */
export class InjectionLog extends Schema.Class<InjectionLog>('InjectionLog')({
  id: Schema.String,
  datetime: Schema.Date,
  drug: Schema.String,
  source: Schema.NullOr(Schema.String),
  dosage: Schema.String,
  injectionSite: Schema.NullOr(Schema.String),
  notes: Schema.NullOr(Schema.String),
  createdAt: Schema.Date,
  updatedAt: Schema.Date,
}) {}

// ============================================
// Input Types
// ============================================

/**
 * Payload for creating a new injection log entry.
 */
export class InjectionLogCreate extends Schema.Class<InjectionLogCreate>('InjectionLogCreate')({
  datetime: Schema.Date,
  drug: Schema.String,
  source: Schema.optionalWith(Schema.String, { as: 'Option' }),
  dosage: Schema.String,
  injectionSite: Schema.optionalWith(Schema.String, { as: 'Option' }),
  notes: Schema.optionalWith(Schema.String, { as: 'Option' }),
}) {}

/**
 * Payload for updating an existing injection log entry.
 */
export class InjectionLogUpdate extends Schema.Class<InjectionLogUpdate>('InjectionLogUpdate')({
  id: Schema.String,
  datetime: Schema.optional(Schema.Date),
  drug: Schema.optional(Schema.String),
  source: Schema.optionalWith(Schema.NullOr(Schema.String), { as: 'Option' }),
  dosage: Schema.optional(Schema.String),
  injectionSite: Schema.optionalWith(Schema.NullOr(Schema.String), {
    as: 'Option',
  }),
  notes: Schema.optionalWith(Schema.NullOr(Schema.String), { as: 'Option' }),
}) {}

/**
 * Payload for deleting an injection log entry.
 */
export class InjectionLogDelete extends Schema.Class<InjectionLogDelete>('InjectionLogDelete')({
  id: Schema.String,
}) {}

/**
 * Parameters for listing injection logs.
 */
export class InjectionLogListParams extends Schema.Class<InjectionLogListParams>('InjectionLogListParams')({
  userId: Schema.String,
  limit: Schema.optionalWith(Schema.Number, { default: () => 50 }),
  offset: Schema.optionalWith(Schema.Number, { default: () => 0 }),
  startDate: Schema.optional(Schema.Date),
  endDate: Schema.optional(Schema.Date),
  drug: Schema.optional(Schema.String), // Filter by specific drug
}) {}
