import { Schema } from 'effect'

// ============================================
// Enums / Literals
// ============================================

/**
 * Supported weight units.
 * - "lbs" = pounds (US)
 * - "kg" = kilograms (metric)
 */
export const WeightUnit = Schema.Literal('lbs', 'kg')
export type WeightUnit = typeof WeightUnit.Type

// ============================================
// Core Domain Type
// ============================================

/**
 * A weight log entry represents a single weight measurement.
 *
 * @property id - UUID, generated by database
 * @property datetime - When the measurement was taken
 * @property weight - The weight value (e.g., 185.5)
 * @property unit - The unit of measurement (lbs or kg)
 * @property notes - Optional free-text notes
 * @property createdAt - When this record was created
 * @property updatedAt - When this record was last modified
 */
export class WeightLog extends Schema.Class<WeightLog>('WeightLog')({
  id: Schema.String,
  datetime: Schema.Date,
  weight: Schema.Number,
  unit: WeightUnit,
  notes: Schema.NullOr(Schema.String),
  createdAt: Schema.Date,
  updatedAt: Schema.Date,
}) {}

// ============================================
// Input Types (for create/update operations)
// ============================================

/**
 * Payload for creating a new weight log entry.
 * id, createdAt, updatedAt are generated server-side.
 */
export class WeightLogCreate extends Schema.Class<WeightLogCreate>('WeightLogCreate')({
  datetime: Schema.Date,
  weight: Schema.Number,
  unit: WeightUnit,
  notes: Schema.optionalWith(Schema.String, { as: 'Option' }),
}) {}

/**
 * Payload for updating an existing weight log entry.
 * All fields optional - only provided fields are updated.
 */
export class WeightLogUpdate extends Schema.Class<WeightLogUpdate>('WeightLogUpdate')({
  id: Schema.String,
  datetime: Schema.optional(Schema.Date),
  weight: Schema.optional(Schema.Number),
  unit: Schema.optional(WeightUnit),
  notes: Schema.optionalWith(Schema.NullOr(Schema.String), { as: 'Option' }),
}) {}

/**
 * Payload for deleting a weight log entry.
 */
export class WeightLogDelete extends Schema.Class<WeightLogDelete>('WeightLogDelete')({
  id: Schema.String,
}) {}

// ============================================
// Query Types
// ============================================

/**
 * Parameters for listing weight logs.
 * Supports pagination and date filtering.
 */
export class WeightLogListParams extends Schema.Class<WeightLogListParams>('WeightLogListParams')({
  limit: Schema.optionalWith(Schema.Number, { default: () => 50 }),
  offset: Schema.optionalWith(Schema.Number, { default: () => 0 }),
  startDate: Schema.optional(Schema.Date),
  endDate: Schema.optional(Schema.Date),
}) {}
