import { Dosage, DrugName, DrugSource, Limit, Notes, Offset } from '../common/domain.js'
import { Schema } from 'effect'
import { InjectionScheduleId } from '../schedule/domain.js'

// ============================================
// Injection Domain Entity ID
// ============================================

/** UUID identifier for injection log entries */
export const InjectionLogId = Schema.String.pipe(Schema.brand('InjectionLogId'))
export type InjectionLogId = typeof InjectionLogId.Type

// ============================================
// Injection Domain Primitives
// ============================================

/** Injection site location */
export const InjectionSite = Schema.String.pipe(Schema.nonEmptyString(), Schema.brand('InjectionSite'))
export type InjectionSite = typeof InjectionSite.Type

/** Injections per week rate */
export const InjectionsPerWeek = Schema.Number.pipe(Schema.nonNegative(), Schema.brand('InjectionsPerWeek'))
export type InjectionsPerWeek = typeof InjectionsPerWeek.Type

// ============================================
// Injection Domain Errors
// ============================================

export class InjectionLogNotFoundError extends Schema.TaggedError<InjectionLogNotFoundError>()(
  'InjectionLogNotFoundError',
  {
    id: Schema.String,
  },
) {}

export class InjectionLogDatabaseError extends Schema.TaggedError<InjectionLogDatabaseError>()(
  'InjectionLogDatabaseError',
  {
    operation: Schema.Literal('insert', 'update', 'delete', 'query'),
    cause: Schema.Defect,
  },
) {}

export const InjectionLogError = Schema.Union(InjectionLogNotFoundError, InjectionLogDatabaseError)
export type InjectionLogError = typeof InjectionLogError.Type
// ============================================
// Core Domain Type
// ============================================

/**
 * An injection log entry represents a single injection event.
 * Used for tracking medication injections (TRT, peptides, etc.)
 *
 * @property id - UUID, generated by database
 * @property datetime - When the injection was administered
 * @property drug - Name of the drug/compound (e.g., "Testosterone Cypionate")
 * @property source - Where the drug came from (e.g., "CVS", "Empower Pharmacy")
 * @property dosage - Amount injected as string (e.g., "200mg", "0.5ml")
 * @property injectionSite - Body location (e.g., "left ventrogluteal", "right deltoid")
 * @property notes - Optional free-text notes
 * @property createdAt - When this record was created
 * @property updatedAt - When this record was last modified
 */
export class InjectionLog extends Schema.Class<InjectionLog>('InjectionLog')({
  id: InjectionLogId,
  datetime: Schema.Date,
  drug: DrugName,
  source: Schema.NullOr(DrugSource),
  dosage: Dosage,
  injectionSite: Schema.NullOr(InjectionSite),
  notes: Schema.NullOr(Notes),
  scheduleId: Schema.NullOr(InjectionScheduleId),
  createdAt: Schema.Date,
  updatedAt: Schema.Date,
}) {}

// ============================================
// Input Types
// ============================================

/**
 * Payload for creating a new injection log entry.
 */
export class InjectionLogCreate extends Schema.Class<InjectionLogCreate>('InjectionLogCreate')({
  datetime: Schema.Date,
  drug: DrugName,
  source: Schema.optionalWith(DrugSource, { as: 'Option' }),
  dosage: Dosage,
  injectionSite: Schema.optionalWith(InjectionSite, { as: 'Option' }),
  notes: Schema.optionalWith(Notes, { as: 'Option' }),
  scheduleId: Schema.optionalWith(InjectionScheduleId, { as: 'Option' }),
}) {}

/**
 * Payload for updating an existing injection log entry.
 */
export class InjectionLogUpdate extends Schema.Class<InjectionLogUpdate>('InjectionLogUpdate')({
  id: InjectionLogId,
  datetime: Schema.optional(Schema.Date),
  drug: Schema.optional(DrugName),
  source: Schema.optionalWith(Schema.NullOr(DrugSource), { as: 'Option' }),
  dosage: Schema.optional(Dosage),
  injectionSite: Schema.optionalWith(Schema.NullOr(InjectionSite), {
    as: 'Option',
  }),
  notes: Schema.optionalWith(Schema.NullOr(Notes), { as: 'Option' }),
  scheduleId: Schema.optionalWith(Schema.NullOr(InjectionScheduleId), { as: 'Option' }),
}) {}

/**
 * Payload for deleting an injection log entry.
 */
export class InjectionLogDelete extends Schema.Class<InjectionLogDelete>('InjectionLogDelete')({
  id: InjectionLogId,
}) {}

/**
 * Parameters for listing injection logs.
 */
export class InjectionLogListParams extends Schema.Class<InjectionLogListParams>('InjectionLogListParams')({
  limit: Schema.optionalWith(Limit, { default: () => 50 as Limit }),
  offset: Schema.optionalWith(Offset, { default: () => 0 as Offset }),
  startDate: Schema.optional(Schema.Date),
  endDate: Schema.optional(Schema.Date),
  drug: Schema.optional(DrugName), // Filter by specific drug
}) {}

/**
 * Payload for bulk assigning injection logs to a schedule.
 */
export class InjectionLogBulkAssignSchedule extends Schema.Class<InjectionLogBulkAssignSchedule>(
  'InjectionLogBulkAssignSchedule',
)({
  ids: Schema.Array(InjectionLogId),
  scheduleId: Schema.NullOr(InjectionScheduleId), // null to unassign
}) {}
