import { Schema } from 'effect'
import { DrugName, DrugSource } from '../common/domain.js'

// ============================================
// Inventory Domain Entity ID
// ============================================

/** UUID identifier for inventory entries */
export const InventoryId = Schema.String.pipe(Schema.brand('InventoryId'))
export type InventoryId = typeof InventoryId.Type

// ============================================
// Inventory Domain Primitives
// ============================================

/** Form of the medication - vial (compounded) or pen (branded) */
export const InventoryForm = Schema.Literal('vial', 'pen')
export type InventoryForm = typeof InventoryForm.Type

/** Status of the inventory item */
export const InventoryStatus = Schema.Literal('new', 'opened', 'finished')
export type InventoryStatus = typeof InventoryStatus.Type

/** Total amount in the vial/pen (e.g., "10mg", "2.4mg") */
export const TotalAmount = Schema.String.pipe(Schema.nonEmptyString(), Schema.brand('TotalAmount'))
export type TotalAmount = typeof TotalAmount.Type

// ============================================
// Inventory Domain Errors
// ============================================

export class InventoryNotFoundError extends Schema.TaggedError<InventoryNotFoundError>()('InventoryNotFoundError', {
  id: Schema.String,
}) {}

export class InventoryDatabaseError extends Schema.TaggedError<InventoryDatabaseError>()('InventoryDatabaseError', {
  operation: Schema.Literal('insert', 'update', 'delete', 'query'),
  cause: Schema.Defect,
}) {}

export const InventoryError = Schema.Union(InventoryNotFoundError, InventoryDatabaseError)
export type InventoryError = typeof InventoryError.Type
// ============================================
// Core Domain Type
// ============================================

/**
 * A GLP-1 inventory item represents a single vial or pen.
 * Used for tracking medication supply.
 *
 * @property id - UUID, generated by database
 * @property drug - Name of the drug (e.g., "Semaglutide (Ozempic)")
 * @property source - Pharmacy source (e.g., "Empower Pharmacy")
 * @property form - 'vial' (compounded) or 'pen' (branded)
 * @property totalAmount - Total mg in the vial/pen (e.g., "10mg")
 * @property status - 'new', 'opened', or 'finished'
 * @property beyondUseDate - BUD for compounded vials (optional)
 * @property createdAt - When this record was created
 * @property updatedAt - When this record was last modified
 */
export class Inventory extends Schema.Class<Inventory>('Inventory')({
  id: InventoryId,
  drug: DrugName,
  source: DrugSource,
  form: InventoryForm,
  totalAmount: TotalAmount,
  status: InventoryStatus,
  beyondUseDate: Schema.NullOr(Schema.Date),
  createdAt: Schema.Date,
  updatedAt: Schema.Date,
}) {}

// ============================================
// Input Types
// ============================================

/**
 * Payload for creating a new inventory item.
 */
export class InventoryCreate extends Schema.Class<InventoryCreate>('InventoryCreate')({
  drug: DrugName,
  source: DrugSource,
  form: InventoryForm,
  totalAmount: TotalAmount,
  status: Schema.optionalWith(InventoryStatus, { default: () => 'new' as const }),
  beyondUseDate: Schema.optionalWith(Schema.Date, { as: 'Option' }),
}) {}

/**
 * Payload for updating an existing inventory item.
 */
export class InventoryUpdate extends Schema.Class<InventoryUpdate>('InventoryUpdate')({
  id: InventoryId,
  drug: Schema.optional(DrugName),
  source: Schema.optional(DrugSource),
  form: Schema.optional(InventoryForm),
  totalAmount: Schema.optional(TotalAmount),
  status: Schema.optional(InventoryStatus),
  beyondUseDate: Schema.optionalWith(Schema.NullOr(Schema.Date), { as: 'Option' }),
}) {}

/**
 * Payload for deleting an inventory item.
 */
export class InventoryDelete extends Schema.Class<InventoryDelete>('InventoryDelete')({
  id: InventoryId,
}) {}

/**
 * Payload for marking an inventory item as finished.
 */
export class InventoryMarkFinished extends Schema.Class<InventoryMarkFinished>('InventoryMarkFinished')({
  id: InventoryId,
}) {}

/**
 * Payload for marking an inventory item as opened.
 */
export class InventoryMarkOpened extends Schema.Class<InventoryMarkOpened>('InventoryMarkOpened')({
  id: InventoryId,
}) {}

/**
 * Parameters for listing inventory.
 */
export class InventoryListParams extends Schema.Class<InventoryListParams>('InventoryListParams')({
  status: Schema.optional(InventoryStatus),
  drug: Schema.optional(DrugName),
}) {}
